### ISSUE TITLE
'NoneType' object has no attribute 'time'

### ISSUE THREAD

**Issue by jerome-tgl** [ayyjayess/beancount-financequote#2]
I can't get it to work on MacOS 10.14.5 with Beancount 2.2.1, sources placed into `beancount/prices/sources` and Finance::Quote installed through CPAN.

Command: `bean-price -e USD:financequote/NASDAQ:GOOG`

Error log:
```
Traceback (most recent call last):
  File "/usr/local/bin/bean-price", line 4, in <module>
    from beancount.prices.price import main; main()
  File "/usr/local/lib/python3.7/site-packages/beancount/prices/price.py", line 369, in main
    price_entries = sorted(price_entries, key=lambda e: e.currency)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/beancount/prices/price.py", line 159, in fetch_price
    srcprice = fetch_cached_price(source, psource.symbol, dprice.date)
  File "/usr/local/lib/python3.7/site-packages/beancount/prices/price.py", line 89, in fetch_cached_price
    if result_naive.time is not None:
AttributeError: 'NoneType' object has no attribute 'time'
```
